<?php

namespace AppBundle\Repository;

/**
 * FizzRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FizzRepository extends \Doctrine\ORM\EntityRepository
{
    // Repository is good !
}
