<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXvit2hu\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXvit2hu/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXvit2hu.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXvit2hu\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXvit2hu\appDevDebugProjectContainer([
    'container.build_hash' => 'Xvit2hu',
    'container.build_id' => '2058404f',
    'container.build_time' => 1613731325,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXvit2hu');
