<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNs8o4l1\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNs8o4l1/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerNs8o4l1.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerNs8o4l1\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerNs8o4l1\appProdProjectContainer([
    'container.build_hash' => 'Ns8o4l1',
    'container.build_id' => 'aeaaacb8',
    'container.build_time' => 1613731618,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNs8o4l1');
