<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0ssyyca\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0ssyyca/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container0ssyyca.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container0ssyyca\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container0ssyyca\appDevDebugProjectContainer([
    'container.build_hash' => '0ssyyca',
    'container.build_id' => 'b4464c66',
    'container.build_time' => 1613481206,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0ssyyca');
